### ISSUE TITLE
AttributeError: 'module' object has no attribute 'logsumexp'

### ISSUE THREAD

**Issue by williamtjordan** [nf-core/deepvariant#24]
Hello,

I am attempting to install this pipeline using Singularity and run the test profile as follows, 

`nextflow run nf-core/deepvariant -profile test,singularity `

and am receiving the following error:

`  Traceback (most recent call last):
    File "/lscratch/1876264.sapelo2/Bazel.runfiles_gbFRRq/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1188, in <module>
      tf.app.run()
    File "/opt/conda/envs/nf-core-deepvariant-1.0/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
      _sys.exit(main(argv))
    File "/lscratch/1876264.sapelo2/Bazel.runfiles_gbFRRq/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1178, in main
      make_examples_runner(options)
    File "/lscratch/1876264.sapelo2/Bazel.runfiles_gbFRRq/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1090, in make_examples_runner
      candidates, examples, gvcfs = region_processor.process(region)
    File "/lscratch/1876264.sapelo2/Bazel.runfiles_gbFRRq/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 806, in process
      self._initialize()
    File "/lscratch/1876264.sapelo2/Bazel.runfiles_gbFRRq/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 747, in _initialize
      self.options.variant_caller_options)
    File "/lscratch/1876264.sapelo2/Bazel.runfiles_gbFRRq/runfiles/com_google_deepvariant/deepvariant/variant_caller.py", line 123, in __init__
      for n_total in range(self.max_cache_coverage + 1)]
    File "/lscratch/1876264.sapelo2/Bazel.runfiles_gbFRRq/runfiles/com_google_deepvariant/deepvariant/variant_caller.py", line 201, in _calc_reference_confidence
      log10_probs = genomics_math.normalize_log10_probs([-1.0, -1.0, -1.0])
    File "/lscratch/1876264.sapelo2/Bazel.runfiles_gbFRRq/runfiles/com_google_deepvariant/third_party/nucleus/util/genomics_math.py", line 261, in normalize_log10_probs
      lse = log10sumexp(log10_probs)
    File "/lscratch/1876264.sapelo2/Bazel.runfiles_gbFRRq/runfiles/com_google_deepvariant/third_party/nucleus/util/genomics_math.py", line 201, in log10sumexp
      return LOG_10_OF_E * scipy.special.logsumexp(
  AttributeError: 'module' object has no attribute 'logsumexp' `

Any information you could provide to fix the problem would be much appreciated.

**Comment by PhilPalmer** [comment]
Hi @williamtjordan, sorry the pipeline isn't working as expected.

I'm not immediately sure what is causing this error. Are you able to upload the `.nextflow.log` file which should be in the directory where you ran your command

**Comment by williamtjordan** [comment]
Hi Phil,

I have attached the nextflow log file in the working directory I used to run the command.

Thank you.

[nextflow.log](https://github.com/nf-core/deepvariant/files/4026497/nextflow.log)

**Comment by PhilPalmer** [comment]
Hi @williamtjordan,

Sorry for taking a short while to getting round to testing this. 

I tested the first command you sent on an AWS instance (with a fresh install of Singularity) & it worked as expected (see [nextflow.log](https://github.com/nf-core/deepvariant/files/4031930/dv_singularity.nextflow.log))

So I am still not completely sure what's causing the issue. Here are some ideas and questions to debug it:

The issue may be to with your Singularity install. **1) How did you Singularity?**

Also, from looking at the log file you sent it looks like you've made a private fork of the repo. **2) Have you made any changes to the pipeline here?**

There is also this error:
```
Authentication is required but no CredentialsProvider has been registered
```

So perhaps you need to provide your GitHub credentials (see [here](https://www.nextflow.io/docs/latest/sharing.html?highlight=git#github-credentials))

It's very strange to have received this error though because the first process (`preprocess_bam`) seems to have run successfully. Perhaps it fails to properly download the reference files from S3 which are only required for the second process. **3) Do you have access to the working directory `/home/wtj04047/work/75/6d0c3d6b79b4a91dbfc2a3887c635d` to see what files are there?**
